import { getElement, getElements } from "../../utils/dom"

/** Gathers every required node before the controller starts making demands. */
export const getFileManagerElements = () => ({
    fileBrowser: getElement<HTMLElement>("#file-browser"),
    browserHero: getElement<HTMLElement>("#browser-hero"),
    browserFooter: getElement<HTMLElement>("#browser-footer"),
    settingsView: getElement<HTMLElement>("#settings-view"),
    settingsButton: getElement<HTMLButtonElement>("#settings-button"),
    settingsReturn: getElement<HTMLButtonElement>("#settings-return"),
    settingsTabs: getElements<HTMLButtonElement>("[data-settings-tab]"),
    settingsPanels: getElements<HTMLElement>("[data-settings-panel]"),
    skipLink: getElement<HTMLAnchorElement>(".skip-link"),
    brandAppName: getElement<HTMLElement>("#brand-app-name"),
    pathPrefix: getElement<HTMLElement>("#path-prefix"),
    siteIntro: getElement<HTMLElement>("#site-intro"),
    footerNodeName: getElement<HTMLElement>("#footer-node-name"),
    fileList: getElement<HTMLElement>("#file-list"),
    searchInput: getElement<HTMLInputElement>("#file-search"),
    backButton: getElement<HTMLButtonElement>("#back-button"),
    breadcrumbs: getElement<HTMLElement>("#breadcrumbs"),
    sortButtons: getElements<HTMLButtonElement>("[data-sort]"),
    emptyState: getElement<HTMLElement>("#empty-state"),
    emptyMessage: getElement<HTMLElement>("#empty-message"),
    visibleCount: getElement<HTMLElement>("#visible-count"),
    visibleSize: getElement<HTMLElement>("#visible-size"),
    entryLabel: getElement<HTMLElement>("#entry-label"),
    authButton: getElement<HTMLButtonElement>("#auth-button"),
    authIcon: getElement<SVGUseElement>("#auth-icon"),
    authLabel: getElement<HTMLElement>("#auth-label"),
    statusLabel: getElement<HTMLElement>("#status-label"),
    accountMenu: getElement<HTMLElement>("#account-menu"),
    accountName: getElement<HTMLElement>("#account-name"),
    signoutButton: getElement<HTMLButtonElement>("#signout-button"),
    identityName: getElement<HTMLElement>("#identity-name"),
    accountSettingsForm: getElement<HTMLFormElement>("#account-settings-form"),
    accountUsername: getElement<HTMLInputElement>("#account-username"),
    accountCurrentPassword: getElement<HTMLInputElement>(
        "#account-current-password",
    ),
    accountNewPassword: getElement<HTMLInputElement>("#account-new-password"),
    accountConfirmPassword: getElement<HTMLInputElement>(
        "#account-confirm-password",
    ),
    accountSettingsError: getElement<HTMLElement>("#account-settings-error"),
    settingsUserList: getElement<HTMLElement>("#settings-user-list"),
    userCount: getElement<HTMLElement>("#user-count"),
    addUserButton: getElement<HTMLButtonElement>("#add-user-button"),
    siteSettingsForm: getElement<HTMLFormElement>("#site-settings-form"),
    siteLabelInput: getElement<HTMLInputElement>("#site-label-input"),
    nodeNameInput: getElement<HTMLInputElement>("#node-name-input"),
    siteIntroInput: getElement<HTMLInputElement>("#site-intro-input"),
    uploadLimitInput: getElement<HTMLInputElement>("#upload-limit-input"),
    defaultSortInput: getElement<HTMLSelectElement>("#default-sort-input"),
    publicDownloadsInput: getElement<HTMLInputElement>(
        "#public-downloads-input",
    ),
    filePreviewsInput: getElement<HTMLInputElement>("#file-previews-input"),
    securitySettingsForm: getElement<HTMLFormElement>(
        "#security-settings-form",
    ),
    newFolderButton: getElement<HTMLButtonElement>("#new-folder-button"),
    uploadButton: getElement<HTMLButtonElement>("#upload-button"),
    filePicker: getElement<HTMLInputElement>("#file-picker"),
    dropOverlay: getElement<HTMLElement>("#drop-overlay"),
    dropMessageText: getElement<HTMLElement>("#drop-message-text"),
    uploadPanel: getElement<HTMLElement>("#upload-panel"),
    uploadList: getElement<HTMLElement>("#upload-list"),
    uploadClear: getElement<HTMLButtonElement>("#upload-clear"),
    previewDialog: getElement<HTMLDialogElement>("#preview-dialog"),
    previewTitle: getElement<HTMLElement>("#preview-title"),
    previewMeta: getElement<HTMLElement>("#preview-meta"),
    previewContent: getElement<HTMLElement>("#preview-content"),
    previewDownload: getElement<HTMLButtonElement>("#preview-download"),
    loginDialog: getElement<HTMLDialogElement>("#login-dialog"),
    loginForm: getElement<HTMLFormElement>("#login-form"),
    usernameInput: getElement<HTMLInputElement>("#username"),
    unlockDialog: getElement<HTMLDialogElement>("#unlock-dialog"),
    unlockForm: getElement<HTMLFormElement>("#unlock-form"),
    unlockName: getElement<HTMLElement>("#unlock-name"),
    unlockPassword: getElement<HTMLInputElement>("#unlock-password"),
    unlockError: getElement<HTMLElement>("#unlock-error"),
    securityDialog: getElement<HTMLDialogElement>("#security-dialog"),
    securityForm: getElement<HTMLFormElement>("#security-form"),
    securityTitle: getElement<HTMLElement>("#security-title"),
    securityCopy: getElement<HTMLElement>("#security-copy"),
    currentPasswordField: getElement<HTMLElement>("#current-password-field"),
    currentPassword: getElement<HTMLInputElement>("#current-password"),
    newPassword: getElement<HTMLInputElement>("#new-password"),
    confirmPassword: getElement<HTMLInputElement>("#confirm-password"),
    securityError: getElement<HTMLElement>("#security-error"),
    securitySubmit: getElement<HTMLButtonElement>("#security-submit"),
    nameDialog: getElement<HTMLDialogElement>("#name-dialog"),
    nameForm: getElement<HTMLFormElement>("#name-form"),
    nameKicker: getElement<HTMLElement>("#name-kicker"),
    nameTitle: getElement<HTMLElement>("#name-title"),
    nameCopy: getElement<HTMLElement>("#name-copy"),
    nameInput: getElement<HTMLInputElement>("#name-input"),
    nameSubmit: getElement<HTMLButtonElement>("#name-submit"),
    deleteDialog: getElement<HTMLDialogElement>("#delete-dialog"),
    deleteForm: getElement<HTMLFormElement>("#delete-form"),
    deleteName: getElement<HTMLElement>("#delete-name"),
    deleteCopy: getElement<HTMLElement>("#delete-copy"),
    userDialog: getElement<HTMLDialogElement>("#user-dialog"),
    userForm: getElement<HTMLFormElement>("#user-form"),
    userDialogTitle: getElement<HTMLElement>("#user-dialog-title"),
    userDialogCopy: getElement<HTMLElement>("#user-dialog-copy"),
    managedUsername: getElement<HTMLInputElement>("#managed-username"),
    managedRole: getElement<HTMLSelectElement>("#managed-role"),
    managedPassword: getElement<HTMLInputElement>("#managed-password"),
    managedPasswordLabel: getElement<HTMLElement>("#managed-password-label"),
    managedPasswordHelp: getElement<HTMLElement>("#managed-password-help"),
    userFormError: getElement<HTMLElement>("#user-form-error"),
    userFormSubmit: getElement<HTMLButtonElement>("#user-form-submit"),
    toast: getElement<HTMLElement>("#toast"),
})
